// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// binSegCpp
List binSegCpp(const arma::mat& tsMat, const int& maxNRegimes);
RcppExport SEXP _rupturesRcpp_binSegCpp(SEXP tsMatSEXP, SEXP maxNRegimesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type tsMat(tsMatSEXP);
    Rcpp::traits::input_parameter< const int& >::type maxNRegimes(maxNRegimesSEXP);
    rcpp_result_gen = Rcpp::wrap(binSegCpp(tsMat, maxNRegimes));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rupturesRcpp_binSegCpp", (DL_FUNC) &_rupturesRcpp_binSegCpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_rupturesRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
