// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_Cost_L1_cwMed_module();
RcppExport SEXP _rcpp_module_boot_Cost_L2_module();
RcppExport SEXP _rcpp_module_boot_Cost_LinearL2_module();
RcppExport SEXP _rcpp_module_boot_Cost_SIGMA_module();
RcppExport SEXP _rcpp_module_boot_Cost_VAR_module();
RcppExport SEXP _rcpp_module_boot_binSegCpp_L1_cwMed_module();
RcppExport SEXP _rcpp_module_boot_binSegCpp_L2_module();
RcppExport SEXP _rcpp_module_boot_binSegCpp_VAR_module();
RcppExport SEXP _rcpp_module_boot_binSegCpp_SIGMA_module();
RcppExport SEXP _rcpp_module_boot_binSegCpp_LinearL2_module();
RcppExport SEXP _rcpp_module_boot_PELTCpp_L1_cwMed_module();
RcppExport SEXP _rcpp_module_boot_PELTCpp_L2_module();
RcppExport SEXP _rcpp_module_boot_PELTCpp_VAR_module();
RcppExport SEXP _rcpp_module_boot_PELTCpp_SIGMA_module();
RcppExport SEXP _rcpp_module_boot_PELTCpp_LinearL2_module();
RcppExport SEXP _rcpp_module_boot_windowCpp_L1_cwMed_module();
RcppExport SEXP _rcpp_module_boot_windowCpp_L2_module();
RcppExport SEXP _rcpp_module_boot_windowCpp_VAR_module();
RcppExport SEXP _rcpp_module_boot_windowCpp_SIGMA_module();
RcppExport SEXP _rcpp_module_boot_windowCpp_LinearL2_module();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_Cost_L1_cwMed_module", (DL_FUNC) &_rcpp_module_boot_Cost_L1_cwMed_module, 0},
    {"_rcpp_module_boot_Cost_L2_module", (DL_FUNC) &_rcpp_module_boot_Cost_L2_module, 0},
    {"_rcpp_module_boot_Cost_LinearL2_module", (DL_FUNC) &_rcpp_module_boot_Cost_LinearL2_module, 0},
    {"_rcpp_module_boot_Cost_SIGMA_module", (DL_FUNC) &_rcpp_module_boot_Cost_SIGMA_module, 0},
    {"_rcpp_module_boot_Cost_VAR_module", (DL_FUNC) &_rcpp_module_boot_Cost_VAR_module, 0},
    {"_rcpp_module_boot_binSegCpp_L1_cwMed_module", (DL_FUNC) &_rcpp_module_boot_binSegCpp_L1_cwMed_module, 0},
    {"_rcpp_module_boot_binSegCpp_L2_module", (DL_FUNC) &_rcpp_module_boot_binSegCpp_L2_module, 0},
    {"_rcpp_module_boot_binSegCpp_VAR_module", (DL_FUNC) &_rcpp_module_boot_binSegCpp_VAR_module, 0},
    {"_rcpp_module_boot_binSegCpp_SIGMA_module", (DL_FUNC) &_rcpp_module_boot_binSegCpp_SIGMA_module, 0},
    {"_rcpp_module_boot_binSegCpp_LinearL2_module", (DL_FUNC) &_rcpp_module_boot_binSegCpp_LinearL2_module, 0},
    {"_rcpp_module_boot_PELTCpp_L1_cwMed_module", (DL_FUNC) &_rcpp_module_boot_PELTCpp_L1_cwMed_module, 0},
    {"_rcpp_module_boot_PELTCpp_L2_module", (DL_FUNC) &_rcpp_module_boot_PELTCpp_L2_module, 0},
    {"_rcpp_module_boot_PELTCpp_VAR_module", (DL_FUNC) &_rcpp_module_boot_PELTCpp_VAR_module, 0},
    {"_rcpp_module_boot_PELTCpp_SIGMA_module", (DL_FUNC) &_rcpp_module_boot_PELTCpp_SIGMA_module, 0},
    {"_rcpp_module_boot_PELTCpp_LinearL2_module", (DL_FUNC) &_rcpp_module_boot_PELTCpp_LinearL2_module, 0},
    {"_rcpp_module_boot_windowCpp_L1_cwMed_module", (DL_FUNC) &_rcpp_module_boot_windowCpp_L1_cwMed_module, 0},
    {"_rcpp_module_boot_windowCpp_L2_module", (DL_FUNC) &_rcpp_module_boot_windowCpp_L2_module, 0},
    {"_rcpp_module_boot_windowCpp_VAR_module", (DL_FUNC) &_rcpp_module_boot_windowCpp_VAR_module, 0},
    {"_rcpp_module_boot_windowCpp_SIGMA_module", (DL_FUNC) &_rcpp_module_boot_windowCpp_SIGMA_module, 0},
    {"_rcpp_module_boot_windowCpp_LinearL2_module", (DL_FUNC) &_rcpp_module_boot_windowCpp_LinearL2_module, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_rupturesRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
