# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PELTCpp <- function(tsMat, penalty, minSize, jump, costFuncObj = NULL) {
    .Call(`_rupturesRcpp_PELTCpp`, tsMat, penalty, minSize, jump, costFuncObj)
}

binSegCpp <- function(tsMat, minSize = 1L, jump = 1L, costFuncObj = NULL) {
    .Call(`_rupturesRcpp_binSegCpp`, tsMat, minSize, jump, costFuncObj)
}

binSegPredCpp <- function(bkps, cost, penalty = 0) {
    .Call(`_rupturesRcpp_binSegPredCpp`, bkps, cost, penalty)
}

