# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PELTCpp <- function(tsMat, penalty, minSize, jump, costFunc = "L2", addSmallDiag = TRUE, epsilon = 1e-6, pVAR = 1L) {
    .Call(`_rupturesRcpp_PELTCpp`, tsMat, penalty, minSize, jump, costFunc, addSmallDiag, epsilon, pVAR)
}

binSegCpp <- function(tsMat, minSize = 1L, jump = 1L, costFunc = "L2", addSmallDiag = TRUE, epsilon = 1e-6, pVAR = 1L) {
    .Call(`_rupturesRcpp_binSegCpp`, tsMat, minSize, jump, costFunc, addSmallDiag, epsilon, pVAR)
}

binSegPredCpp <- function(bkps, cost, penalty = 0) {
    .Call(`_rupturesRcpp_binSegPredCpp`, bkps, cost, penalty)
}

