# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

peltL2 <- function(tsMat, penalty, minSize, jump) {
    .Call(`_rupturesRcpp_peltL2`, tsMat, penalty, minSize, jump)
}

binSegCpp <- function(tsMat, minSize = 1L, jump = 1L) {
    .Call(`_rupturesRcpp_binSegCpp`, tsMat, minSize, jump)
}

binSegPredCpp <- function(bkps, cost, penalty = 0) {
    .Call(`_rupturesRcpp_binSegPredCpp`, bkps, cost, penalty)
}

